-- Create a example tables
CREATE TABLE MYSALARY (EMPLOYEEID INT, SALARY FLOAT)
INSERT INTO MYSALARY VALUES (1, 10000)
INSERT INTO MYSALARY VALUES (2, 8000)
INSERT INTO MYSALARY VALUES (3, 6000)

CREATE TABLE MYORDER (ORDERNUMBER INT, ORDERNAME VARCHAR(20), ID INT)
INSERT INTO MYORDER VALUES(1, 'LOL', 1)
INSERT INTO MYORDER VALUES(2, 'LEL', 2)
INSERT INTO MYORDER VALUES(3, 'ROFL', 7)
INSERT INTO MYORDER VALUES(4, 'XD', 8)

-- Have a look at it
SELECT * FROM MYSALARY

-- Get the Average Salary
SELECT AVG(SALARY) FROM MYSALARY

-- Get the amount of entries for a column/ a DF
SELECT COUNT(SALARY) FROM MYSALARY
SELECT COUNT(*) FROM MYSALARY

-- Get the sum/min/max of the salary
SELECT SUM(SALARY) FROM MYSALARY
SELECT MIN(SALARY) FROM MYSALARY
SELECT MAX(SALARY) FROM MYSALARY

SELECT * FROM MYORDER

-- CONCAT Str
PRINT CONCAT('STR1', 'STR2')
SELECT ORDERNUMBER, ORDERNAME, CONCAT(ORDERNUMBER, ' - ', ORDERNAME) AS CONCATEDTEXT FROM MYORDER

-- Get a random number
PRINT RAND()

-- Subset the first/ last n letters from a string
SELECT ORDERNUMBER, ORDERNAME, LEFT(ORDERNAME, 2) AS NewCol FROM MYORDER
SELECT ORDERNUMBER, ORDERNAME, RIGHT(ORDERNAME, 2) AS NewCol FROM MYORDER

-- Substring
SELECT ORDERNUMBER, ORDERNAME, SUBSTRING(ORDERNAME, 2, 1) AS NewCol FROM MYORDER -- START OF INDEX, AMOUNT OF CHARS
SELECT ORDERNUMBER, ORDERNAME, SUBSTRING(ORDERNAME, 1, 2) AS NewCol FROM MYORDER

-- TO Lower/ Upper
SELECT ORDERNUMBER, ORDERNAME, LOWER(ORDERNAME) AS NewCol FROM MYORDER
SELECT ORDERNUMBER, ORDERNAME, UPPER(ORDERNAME) AS NewCol FROM MYORDER

-- Length of a string
SELECT ORDERNUMBER, ORDERNAME, LEN(ORDERNAME) AS NewCol FROM MYORDER

-- Play around with LOWER, UPPER, CONCAT, ...
SELECT ORDERNUMBER, ORDERNAME, CONCAT(UPPER(LEFT(ORDERNAME, 1)), LOWER(SUBSTRING(ORDERNAME, 2, LEN(ORDERNAME)))) AS NewCol FROM MYORDER

-- TRIM
SELECT '    MYTEXT    '

SELECT LTRIM('    MYTEXT    ')
SELECT RTRIM('    MYTEXT    ')
SELECT LTRIM(RTRIM('    MYTEXT    '))







